[package]
name = "cs492-concur-homework"
version = "0.1.0"
authors = ["Jeehoon Kang <jeehoon.kang@kaist.ac.kr>"]
edition = "2018"

[dependencies]
itertools = "0.8.2"
static_assertions = "1.1.0"
crossbeam-epoch = "0.8.0"
crossbeam-utils = "0.7.0"
arr_macro = "0.1.3"
either = "1.5.3"
lock = { git = "https://github.com/kaist-cp/cs492-concur" }
rand = "0.7.2"
